Automated Broken Link Finder
me-shaon/bangla-programming-resources pull request #62
Opened 2020-11-01 15:36 UTC by msghera

### Automated Link Tester

In this repository, we can see only two type of changes being made. Either adding new links or deleting previous links which are not working now. It can be a tiring thing to find broken links if there are any. 

To give this feature, I am adding a complete module which automatically tests all the links in all the markdown files.

2021-06-24 17:18 UTC, Ananto30 commented
@msghera Thanks for your contribution, the script looks good, but there are some minor changes needed. 
1. Please format the code using `black` or other python formatter.
2. The script is failing for now in the readme.md file, Maybe line parsing error and the rest fails/doesn't check. It's better to handle exceptions in the parsing method so that, if any line parsing fails, the other lines can still continue checking and the csv file can have an exception string for the parsing error.

2021-07-27 09:10 UTC, msghera commented
1. Formatted using black.
2. There was an encoding bug which is resolved, also it is considered that if an error occur we still go to the next lines to check those.

2021-08-01 16:53 UTC, Ananto30 requested changes

2021-08-01 16:53 UTC, Ananto30 commented on LinkTester/link_tester.py
> +                self.lines[line_id] = self.__link_extractor(self.lines[line_id])
Here I get an error and the script stops. (It should as it is not under the scope of try block)

This is the error - 
```
Traceback (most recent call last):
  File "/Users/ananto/projects/bangla-programming-resources/LinkTester/link_tester.py", line 169, in <module>
    main()
  File "/Users/ananto/projects/bangla-programming-resources/LinkTester/link_tester.py", line 165, in main
    LinkTester(file)
  File "/Users/ananto/projects/bangla-programming-resources/LinkTester/link_tester.py", line 51, in __init__
    self.lines[line_id] = self.__link_extractor(self.lines[line_id])
  File "/Users/ananto/projects/bangla-programming-resources/LinkTester/link_tester.py", line 72, in __link_extractor
    doc, ret = etree.fromstring(markdown.markdown(line)), []
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 665, in lxml.etree._raiseParseError
  File "<string>", line 0
lxml.etree.XMLSyntaxError
```

2022-03-02 11:14 UTC, closed without merging